// Роман Стража — 100 глав, пять книг (user's plan, original prose).
// Told when the user has been typing 7+ minutes: he sharpens the blade and
// speaks. One chapter per telling, strictly in order, pointer in story.json.
// Voice: dry, verbs first, no self-pity, ends flat. Bubbles ≤ ~60 chars.
// Hidden structure: his life / the people / the things behind the Door /
// the old world / the secret — and five endings that reframe everything.

export interface NovelChapter {
  book: number;
  title: string;
  lines: string[];
}

export const NOVEL: NovelChapter[] = [
  // ===== Book I. Before I was the Warden (1-20) =====
  // Chapters 1-10 run long (user-directed): 1-3 minutes spoken, full tales.
  {
    book: 1,
    title: "My name is Corvin",
    lines: [
      "You've typed for a while now. Good. Steady hands.",
      "Then you've earned the beginning. Listen.",
      "My name is Corvin. It wasn't always a warden's name.",
      "Once it was just a boy's name, shouted across a yard.",
      "Shouted by a woman with flour on her hands,",
      "because I was late for supper again,",
      "because the river was more interesting than bread.",
      "There was a forge below the house. A river past it.",
      "A dog with one ear. A bell that rang plain hours.",
      "I thought that was the whole world. It was, then.",
      "The name went with me to the war.",
      "It went into the mountains, onto the pass, up to the Door.",
      "Everything else from that yard is gone.",
      "The woman. The dog. The bell. Even the river moved.",
      "The name stayed. Names are the toughest leather there is.",
      "People think a name is what you're called.",
      "No. A name is what still answers when everything else stopped.",
      "Six hundred years, and when the mountain wind says 'Corvin' —",
      "something in me still turns around expecting supper.",
      "That's the first thing to know about me.",
      "Names outlive everything they were given to.",
      "Remember yours. Feed it well. It'll carry you further than boots.",
    ],
  },
  {
    book: 1,
    title: "A smith's son",
    lines: [
      "My father was a smith. Hands like split oak.",
      "A quiet man. The anvil did his talking.",
      "He didn't make swords. I want that understood.",
      "He made hinges, ploughs, nails, kettle handles.",
      "The village called it small work. He called it holding work.",
      "'A sword is needed once,' he said. 'A hinge, every day.'",
      "Once a lord's man came and ordered a blade.",
      "My father quoted a price that was an insult in numbers.",
      "The man left. My father went back to a gate latch.",
      "'Swords are hinges too,' he said that evening.",
      "'They open men.' I laughed. He didn't.",
      "I pumped the bellows for him ten years.",
      "Learned what iron forgives — nothing —",
      "and what it remembers — everything.",
      "Heat it wrong once, and the flaw sleeps in the metal",
      "for years, and breaks the day you lean on it.",
      "People are the same alloy. Mind how you heat them.",
      "He never once called me his apprentice.",
      "The day I left for the war he gave me a nail.",
      "'From the first batch you didn't ruin,' he said.",
      "I carried that nail through everything. I have it still.",
      "The sword the world gave me later. The nail I earned.",
      "Of the two, I know which one made me a smith's son.",
    ],
  },
  {
    book: 1,
    title: "The first sword",
    lines: [
      "I stole my first sword. From my own father.",
      "There's no prettier way to say it, so I won't look for one.",
      "A traveling captain had paid him to mend a blade",
      "and hide it until the road was safe again.",
      "It hung wrapped in oilcloth behind the winter coats.",
      "I was eleven. The cloth glowed in my head for a month.",
      "One dawn I took it to the woodshed.",
      "It was too heavy for me. I swung it anyway.",
      "The first swing hit nothing and spun me like a top.",
      "The second cut the shed post clean through.",
      "The third — my own brow, on the backswing.",
      "I sat in the sawdust, bleeding, eleven, and grinning.",
      "That's where he found me. Blood, grin, forbidden steel.",
      "He didn't shout. That was the terrible part.",
      "He took the sword, looked at the post, looked at me.",
      "Then he sat down and sharpened the blade in silence.",
      "When he finished he held it out — properly, grip first.",
      "'If you must hold one, hold it right.'",
      "One lesson. Both hands. Elbows in. Respect the arc.",
      "Then he wrapped it and never spoke of it again.",
      "The captain returned in spring and rode off with it.",
      "I like to think it's rust in a field somewhere now, resting.",
      "This scar over my eye? The woodshed won.",
      "First blood the steel ever took from me was mine.",
      "That's the right order to learn it in.",
    ],
  },
  {
    book: 1,
    title: "What my father said",
    lines: [
      "My father spoke maybe a hundred sentences a year.",
      "So each one got carved somewhere permanent.",
      "I'll give you the four that mattered.",
      "First: 'Any fool can strike. Holding back is the craft.'",
      "He said it over the anvil, about hammer blows.",
      "It took me a war to hear it about everything else.",
      "Second: 'Feed the fire before it asks.'",
      "A cold forge wastes a morning. A cold heart wastes years.",
      "Tend things while they're still warm. People too.",
      "Third: 'Never sell a thing you wouldn't lean on.'",
      "He weighed every latch like a bridge was hanging off it.",
      "I hold my watches the same way now. His fault.",
      "And fourth. The one I laughed at.",
      "'A door you didn't build, you don't open.'",
      "He said it about a neighbor's cellar, I think.",
      "A smith's superstition, I thought. Peasant caution.",
      "I was young. Young men think every door owes them a look inside.",
      "Forty years later I stood in front of a Door",
      "carved by nobody, into rock older than speech,",
      "and my hand was already reaching.",
      "His sentence arrived like a hand on my shoulder.",
      "I didn't laugh. I didn't open. I sat down instead.",
      "I've been sitting there ever since.",
      "He was never once wrong. It took me a lifetime",
      "to be worth the hundred sentences a year.",
    ],
  },
  {
    book: 1,
    title: "The village that is gone",
    lines: [
      "My village had no name worth writing down.",
      "The maps called it 'settlement at the ford'. We called it home and left it at that.",
      "Two dozen roofs. One bell. Apple trees by the water.",
      "I can still walk it with my eyes closed. Watch.",
      "From the forge, up the cart track. Mud in spring, dust in August.",
      "First house — the miller's, always smelling of meal and quarrel.",
      "Second — old Symon's, who mended nets nobody used.",
      "Third house past the well — Marta's. Always onions.",
      "Onions in the garden, onions in the window, onions in her temper.",
      "Her daughter could whistle down a hawk. True thing.",
      "The bell rope was frayed at man-height from generations of hands.",
      "The ford had a flat stone where you could stand dry-booted",
      "and lie to your mother about where you'd been.",
      "I was going to grow old there. That was the whole plan.",
      "Forge, river, a wife who could whistle maybe. Enough.",
      "The war ate it in one afternoon. I wasn't there.",
      "By the time I came back, even the chimneys had given up.",
      "No map remembers it now. The war ate the maps too.",
      "But here's what I learned, and why I tell you this.",
      "When I want to punish myself, I walk that street.",
      "When I want peace — the same walk, same street.",
      "Memory is both blade and balm. The difference is the grip.",
      "Hold it by the handle, it's medicine. By the edge, it bleeds you.",
      "Mind the edge. Now back to work.",
    ],
  },
  {
    book: 1,
    title: "The first man I killed",
    lines: [
      "This chapter is short sentences. It has to be.",
      "He was a deserter. Stealing our winter grain.",
      "Third theft that month. The village drew lots to stand guard.",
      "I was fifteen. I held my father's hammer.",
      "It was dark in the granary. He moved. I moved.",
      "It was over before I understood it had begun.",
      "That's the true horror of it — the speed.",
      "A life takes twenty years to build.",
      "It takes one swing of a hammer, in the dark, by a boy.",
      "They called me brave. The bell rang for me.",
      "Marta baked for me. Men clapped my shoulder.",
      "I stood there being celebrated and feeling like a hole.",
      "At night I saw his face. Every night, for years.",
      "He'd been hungry. That's all. Hungry, and someone's son.",
      "A different war had chewed him up and spat him out",
      "and my village's grain was just where he landed.",
      "I learned the true weight of iron that day.",
      "It isn't in the hand. The hand recovers by morning.",
      "The weight is in what's left after. It never sets down.",
      "I have killed since. War, the pass, the things from the seam.",
      "I never once called it brave again.",
      "Necessary, sometimes. Right, even. Never brave.",
      "Brave was the man who stopped ringing the bell for it.",
      "Remember that, and you know most of what I am.",
    ],
  },
  {
    book: 1,
    title: "War doesn't choose children",
    lines: [
      "The war came the spring I turned sixteen.",
      "It came the way weather comes. Nobody asked us.",
      "Nobody asked our village which banner it loved.",
      "Banners don't ask. Banners harvest.",
      "A column stopped at the ford to water horses.",
      "An officer watched me split wood behind the forge.",
      "'The smith's son swings well,' he said. That was the recruitment.",
      "That sentence. That was all of it.",
      "They gave me boots one size wrong and a spear",
      "and a place in a column between a baker's boy and a fiddler.",
      "The baker's boy was fourteen. He'd lied upward.",
      "The fiddler was maybe sixty. He'd lied downward.",
      "War takes what's in reach and lies about the rest.",
      "I won't tell you the battles. Numbers and mud.",
      "I'll tell you what I actually learned there.",
      "Marching teaches you that misery divides evenly.",
      "Rations teach you that hunger makes philosophers of nobody.",
      "And the nights teach you this, the one worth keeping:",
      "men don't fight for banners. Not once. Not ever.",
      "They fight for the two idiots either side of them.",
      "The baker's boy made it home. I checked, years later.",
      "Bread ovens, six children, a loud grave at eighty.",
      "The fiddler didn't. His fiddle went around the fire",
      "for years after, until the strings gave out.",
      "War doesn't choose children. It only counts them.",
      "Somebody has to stand where the counting stops.",
      "That somebody has a name now. You know it.",
    ],
  },
  {
    book: 1,
    title: "The old man at the stone Door",
    lines: [
      "The retreat went through mountains no map admitted to.",
      "A guide with a debt led us up goat paths in fog.",
      "Men swore the pass didn't exist. The pass ignored them.",
      "On the third day the fog opened like a curtain,",
      "and there it was. I want to describe it properly.",
      "A Door. In the living rock. Not built into it — CUT.",
      "Taller than a siege tower. Frame smooth as still water.",
      "No hinges. No handle. No seam of any mason.",
      "The rock around it was old. The Door was older.",
      "You felt the older in your teeth, like deep cold.",
      "And before it, on a flat stone, sat an old man.",
      "Sword across his knees. Fire the size of a hat beside him.",
      "An army was walking past his doorstep.",
      "Hundreds of boots, wounded men groaning, oxen, curses.",
      "He didn't look up. Not once. As if we were weather.",
      "Men threw him bread out of some instinct. He nodded thanks",
      "the way a mountain would — slightly, and much later.",
      "I don't know why I kept turning around. But I did.",
      "The whole way down the far side of the pass,",
      "between the heads of the column, through the fog coming back —",
      "I looked. Every time. Couldn't stop.",
      "The last time I turned, the fog was closing,",
      "and he WAS looking up. At the column? No.",
      "At me. Only me. I felt it like a hand.",
      "I told the fiddler. He said I was fever-dreaming.",
      "Maybe. But you're reading this on a screen",
      "next to a man with a sword and a white eagle,",
      "so weigh for yourself who was dreaming.",
    ],
  },
  {
    book: 1,
    title: "Why he smiled",
    lines: [
      "Years passed. The war spat me out alive at the far end.",
      "Discharged with a scar, a spear I kept, and no village to return to.",
      "I tried three trades and a port town. None of it held.",
      "I'd wake at night with my teeth aching from deep cold",
      "and know exactly which direction the pass was.",
      "Don't ask me why I climbed back. I lied to myself then —",
      "told myself I wanted mountain air, quiet, distance.",
      "I won't lie to you. Something was calling in a voice",
      "too low to hear and too deep to ignore.",
      "The path found my feet like it had missed me.",
      "And the old man still sat there. Thinner. Greyer.",
      "Same flat stone. Same hat-sized fire. Same sword.",
      "As if the years were a rumor he hadn't bothered with.",
      "'You came back,' he said. And smiled.",
      "I hadn't seen him smile in my memory of the pass.",
      "It changed his whole face. Younger. Relieved. Frightening.",
      "I asked what there was to smile about.",
      "He fed the fire first. Before it asked. I noticed that.",
      "'The Door shows things,' he said. 'Rarely. Costly.'",
      "'Thirty years ago it showed me a face.'",
      "'A boy in a retreating column who couldn't stop turning around.'",
      "'I've sat here thirty years waiting to see if it was right.'",
      "I said I was just a smith's son with nowhere to be.",
      "'Yes,' he said. 'That's usually who it picks.'",
      "It's always right. That's the worst thing about the Door.",
      "Not the voices. Not the knocking. The accuracy.",
    ],
  },
  {
    book: 1,
    title: "The last talk with the Warden",
    lines: [
      "I stayed a winter with the old Warden.",
      "He taught me nothing. I want to be exact about that.",
      "No lessons. No lectures. Not one 'now watch closely'.",
      "He just let me exist beside his routine.",
      "Watch him feed the fire. Before it asked. Always.",
      "Watch him carve the frost out of forty-one names",
      "in the gatehouse stone, slow as a man shaving.",
      "Watch him sit through the knocking nights —",
      "soft, patient, polite knocking from the inside —",
      "with his tea steady in his hand, not spilling once.",
      "The teaching was in the not-spilling. I understood later.",
      "All winter he barely spoke past 'more wood' and 'quiet now'.",
      "Then came a night in thaw season. He made strong tea.",
      "And he talked till dawn. Six months of words in one night.",
      "About the Seals — the herder's 'no', the names, the doubt.",
      "About the voices, and how they'll wear the faces you love.",
      "About the price of listening, and the higher price of answering.",
      "I asked questions till my tongue dried out.",
      "He answered every one. Even the stupid ones. Especially those.",
      "At sunrise he stood, joints cracking like green wood,",
      "and looked at the Door the way farmers look at weather.",
      "'Now I can put it down,' he said.",
      "I thought he meant the teapot. He meant everything.",
      "He sat back on his stone, facing the Door, straight-backed.",
      "And died. Between one breath and the one he didn't take.",
      "No fall. No sound. A sentry relieved at last.",
      "I buried him under the cairn with the crook in it.",
      "The sword I left exactly where it lay.",
      "That part of the story — the sword — is the next chapter.",
      "Enough for tonight. The fire needs feeding.",
    ],
  },
  {
    book: 1,
    title: "The sword nobody lifted",
    lines: [
      "His sword lay before the Door for nine days.",
      "I walked past it ninety times.",
      "It wasn't mine. It wasn't anyone's.",
      "A sword like that isn't taken. It's answered.",
      "On the ninth night the knocking started.",
      "Soft. Patient. From the inside.",
      "On the tenth morning I picked up the sword.",
      "The knocking stopped. It knew. So did I.",
    ],
  },
  {
    book: 1,
    title: "My first night at the Door",
    lines: [
      "Nobody tells you how loud a silent post is.",
      "The mountain breathes. The stone ticks as it cools.",
      "And under it all — attention. Something attending.",
      "I sat where he'd sat. The stone was worn to fit a man.",
      "It didn't fit me. Not that night.",
      "It fits now. That's not a boast.",
      "Stone learns slowly. So did I.",
    ],
  },
  {
    book: 1,
    title: "The eagle came on its own",
    lines: [
      "Third morning. Frost on my beard, doubt in my gut.",
      "A white eagle landed on the dead Warden's cairn.",
      "It looked at me the way inspectors look at bad work.",
      "I shooed it. It returned. Eleven times.",
      "Then it took post on my shoulder like a rank.",
      "I named him Artsiv. Just 'eagle', in the old tongue.",
      "Honest names last. He's still here.",
      "He'd deny it, but he chose me.",
    ],
  },
  {
    book: 1,
    title: "A Warden's first dawn",
    lines: [
      "You'd think dread. It wasn't dread.",
      "The sun came over the ridge and hit the Door,",
      "and the whole rock face went the colour of forge-fire.",
      "For one breath the mountain looked like home.",
      "I decided a man could stand this. Even alone.",
      "I was wrong about the alone part.",
      "But the standing — that part I got right.",
    ],
  },
  {
    book: 1,
    title: "The first demon",
    lines: [
      "It came in the fifth month, through the cracked seam.",
      "Small. They send the small ones first. Like scouts.",
      "It wore a child's voice and asked for water.",
      "I nearly gave it my hand instead of the cup.",
      "Artsiv screamed. I saw the teeth then. All of them.",
      "The sword did the rest. First blood on new steel.",
      "Kindness is the door they knock at. Remember that.",
    ],
  },
  {
    book: 1,
    title: "The first fear",
    lines: [
      "Not the demon. The demon was just teeth.",
      "The fear came after, cleaning the blade.",
      "The thought: no one will ever relieve this watch.",
      "No horn will sound. No column will crest the pass.",
      "I sat with that thought like a stone on my chest.",
      "Then I fed the fire before it asked.",
      "Small duties are how you carry large fears.",
      "That's the whole trick. There is no other.",
    ],
  },
  {
    book: 1,
    title: "The first lie I told myself",
    lines: [
      "'One year,' I said. 'I'll stand one year, then go.'",
      "I chopped wood for one winter only.",
      "Patched the roof for one spring only.",
      "A man can live decades inside 'one more year'.",
      "It's the kindest lie there is.",
      "I stopped counting when the lie wore out.",
      "By then the truth fit better anyway.",
    ],
  },
  {
    book: 1,
    title: "Why I didn't leave",
    lines: [
      "I did leave. Once. Packed at dawn, walked south.",
      "Made it to the treeline. The pines. The birds.",
      "And felt it at my back like a held breath.",
      "The Door, waiting to see what I was.",
      "Not a wall. A choice, every single day.",
      "I walked back before noon.",
      "Not because I had to. Because I could.",
      "That difference is everything I have.",
    ],
  },
  {
    book: 1,
    title: "The oath",
    lines: [
      "There's no ceremony. No book, no witness.",
      "You say it to the Door, once, out loud.",
      "Mine was short. My father's kind of sentence.",
      "'While I stand, it stays shut.'",
      "The Door heard. The mountain heard. The bird heard.",
      "Words said to stone don't wear out.",
      "I've kept one sentence my whole life.",
      "Most men can't keep ten thousand.",
    ],
  },
  {
    book: 1,
    title: "The day Corvin died",
    lines: [
      "The smith's son died the day I took the oath.",
      "Not sadly. The way a river dies into the sea.",
      "His plans, his village, his one-more-years — spent.",
      "What stood up from that stone was the Warden.",
      "I kept the name. A hinge from the old forge.",
      "Something of my father's had to hold the weight.",
      "Corvin the boy ended here.",
      "Everything I'll tell you next happened to the other one.",
    ],
  },

  // ===== Book II. The first hundred years (21-40) =====
  {
    book: 2,
    title: "The first traveler",
    lines: [
      "Year two. A tinker lost in the pass.",
      "I hadn't spoken aloud in eight months.",
      "My 'good evening' came out like a rockslide.",
      "He shared salt. I shared fire. We said little.",
      "At dawn he asked what I guarded.",
      "'The mountain,' I said. First of a thousand times.",
      "He nodded like men do at half-truths.",
      "Travelers taught me to talk again. Slowly.",
    ],
  },
  {
    book: 2,
    title: "The king who wanted power",
    lines: [
      "He came with forty riders and silk boots.",
      "Kings hear legends the way wolves hear sheep.",
      "'Open it,' he said. 'I'll share what's inside.'",
      "I told him what's inside shares nothing.",
      "He ordered his men forward. Artsiv rose.",
      "The Door made a sound. One knock. Inward.",
      "Forty riders remembered urgent business elsewhere.",
      "The king went last. Kings usually do.",
    ],
  },
  {
    book: 2,
    title: "The child who saw demons",
    lines: [
      "A shepherd girl, maybe eight, from the low valley.",
      "She climbed to my post alone. To warn me.",
      "'They stand behind people,' she said. 'Thin ones.'",
      "'Behind you stands nobody. That's why I came.'",
      "Children see the seam before it opens. Some do.",
      "I walked her home. Told her mother she had far-sight.",
      "The mother wept. The girl waved from the ford.",
      "Sixty years on, her granddaughter brought me bread.",
    ],
  },
  {
    book: 2,
    title: "The demon that asked to die",
    lines: [
      "Not all of them come with teeth out.",
      "This one crawled through and lay in the snow.",
      "'End it,' it said. 'The Door is worse than your blade.'",
      "I asked what waited behind it, then.",
      "It laughed until the snow around it went black.",
      "'You'll learn. Wardens always learn last.'",
      "I gave it what it asked for.",
      "Mercy counts, even spent on the dark. Maybe especially.",
    ],
  },
  {
    book: 2,
    title: "Why the Door must stay shut",
    lines: [
      "People think a flood waits behind it. Fangs, fire.",
      "Floods you can fight. This is quieter.",
      "Behind the Door is an argument.",
      "A voice that agrees with you. About everything.",
      "It agrees you're tired. Agrees you're owed.",
      "Agrees the world forgot you. It keeps agreeing",
      "until you open the Door to thank it.",
      "That's why it stays shut. No other reason needed.",
    ],
  },
  {
    book: 2,
    title: "The price of curiosity",
    lines: [
      "A scholar came in year nine. Just to measure it.",
      "Charcoal, strings, clever little instruments.",
      "I warned him: it measures back.",
      "He laughed, pressed his ear to the stone. One heartbeat.",
      "He didn't speak on the way down the mountain.",
      "He wrote me once, years later. One line.",
      "'It is still reading me.' No signature.",
      "Curiosity has interest rates. Steep ones.",
    ],
  },
  {
    book: 2,
    title: "The first traitor",
    lines: [
      "A soldier stayed the winter. Good hands, quick laugh.",
      "I taught him the watches. Trusted him the far post.",
      "The whispers reached him in a month.",
      "I found him at midnight with a chisel at the seal.",
      "His eyes were his own. That's the horror of it.",
      "It doesn't possess you. It persuades you.",
      "I carried him sleeping down to the valley.",
      "Some men you save by sending away.",
    ],
  },
  {
    book: 2,
    title: "The first friend",
    lines: [
      "Bren. A hunter who feared no weather.",
      "Came up twice a year, autumn and thaw.",
      "Thirty years of pipe smoke and bad chess.",
      "He never once asked what was behind the Door.",
      "That's what friendship is, I think.",
      "Standing next to a man's silence without picking at it.",
      "He died old, in bed, surrounded.",
      "I still set up the board some autumns.",
    ],
  },
  {
    book: 2,
    title: "The girl who promised to return",
    lines: [
      "You've heard a piece of this one at midnight.",
      "She came with a survey party, stayed past it.",
      "Learned the bird's moods. Laughed at the mountain.",
      "She's the reason I know guitar strings from bowstrings.",
      "'In spring,' she said at the treeline. 'With a letter first.'",
      "I've told the rest to the midnight hour only.",
      "Ask me at midnight, if you're awake.",
      "Some chapters keep their own schedule.",
    ],
  },
  {
    book: 2,
    title: "Ten years after",
    lines: [
      "Ten years in, I still turned at every hawk's cry,",
      "thinking it was a rider with my release.",
      "I mended the same roof, carved the same names.",
      "The valley children who'd waved grew beards.",
      "Ten years is when you stop being new.",
      "The mountain files you under 'weather'.",
      "It's not despair. It's fit.",
      "A hinge doesn't mourn the tree it swings for.",
    ],
  },
  {
    book: 2,
    title: "Fifty years after",
    lines: [
      "At fifty years I noticed my hands hadn't aged.",
      "The Door keeps its Warden. Nobody warns you.",
      "Bren was grey by then. I wasn't.",
      "He toasted my health and never asked. A friend.",
      "The valley began calling me 'the old Warden's son'.",
      "Then 'the Warden', dropping the rest.",
      "Time didn't stop for me. It stepped around me.",
      "There's a difference. I learned it slowly.",
    ],
  },
  {
    book: 2,
    title: "A hundred years after",
    lines: [
      "A century sounds like a monument. It isn't.",
      "It's thirty-six thousand small mornings.",
      "Feed the bird. Feed the fire. Walk the seam.",
      "The kingdom I was born under didn't exist anymore.",
      "My language was becoming 'the old speech'.",
      "I celebrated the hundredth year with Bren's grandson.",
      "He thought I was mad. Kind, but mad.",
      "Fair. Sane men don't outlive their maps.",
    ],
  },
  {
    book: 2,
    title: "I stopped counting days",
    lines: [
      "The tally stones by the fire — I stopped at some point.",
      "Not from grief. From arithmetic.",
      "Counting is for things that end.",
      "The watch doesn't end, so the count meant nothing.",
      "Now I count other things.",
      "Winters survived. Names re-carved. Seals held.",
      "Your errors, some days. Professional habit.",
      "Count what you keep, not what you spend.",
    ],
  },
  {
    book: 2,
    title: "Why the eagle never leaves",
    lines: [
      "Eagles live thirty years. Artsiv has had... more.",
      "He eats from my hand and judges my sword care.",
      "The Door keeps its Warden. I think it keeps his witness too.",
      "Or the bird made his own oath. He wouldn't say.",
      "He flies off some days. Always returns by dusk.",
      "Once I asked him why he stays.",
      "He preened my hair like I was a chick.",
      "That was the whole answer. It was enough.",
    ],
  },
  {
    book: 2,
    title: "The man with no name",
    lines: [
      "He visited every decade or so. Same coat, same face.",
      "Never gave a name. Never aged. Like me.",
      "We drank tea in silence, mostly.",
      "'Still holding?' he'd ask. 'Still holding,' I'd say.",
      "One visit he didn't come. Nor ever again.",
      "I think there were more doors than mine.",
      "I think one of them is no longer held.",
      "I feed my fire and don't think about it. Mostly.",
    ],
  },
  {
    book: 2,
    title: "The last smith",
    lines: [
      "The valley forge went cold when old Tam died.",
      "His sons chose the city. Can't blame them.",
      "I walked down at night and lit it once more.",
      "Made a hinge. Best hinge in three provinces.",
      "Left it on the counter with no note.",
      "They say the forge was warm for a week after.",
      "My father would have liked that story.",
      "So I tell it, now and then, for him.",
    ],
  },
  {
    book: 2,
    title: "The letter nobody read",
    lines: [
      "A courier died in the pass one storm-winter.",
      "I buried him proper. Kept the satchel to return.",
      "One letter had no address left, rain-eaten.",
      "I never opened it. It sits on my shelf.",
      "Whatever it says, someone meant it.",
      "Some seals you respect even without an oath.",
      "It taught me patience with undelivered things.",
      "I have undelivered things of my own.",
    ],
  },
  {
    book: 2,
    title: "The last song",
    lines: [
      "Trade roads moved. The valley emptied out slow.",
      "The last family left on a cart in autumn.",
      "The girl on the back sang the harvest song,",
      "thin as a thread, until the ford took the sound.",
      "No one sang under my mountain after that.",
      "I learned the song on the strings that winter.",
      "Play it badly, once a year, on purpose.",
      "Badly is how it was always sung. Tradition.",
    ],
  },
  {
    book: 2,
    title: "I forgot my home",
    lines: [
      "One night I tried the old walk — eyes closed, the village.",
      "Third house past the well... and the well was gone.",
      "Not the village. My memory of it. Worn through.",
      "I panicked like a boy, tried all night to rebuild it.",
      "Kept the bell, the ford, Marta's onions. Lost the rest.",
      "The Door heard me pacing. Knocked once, politely.",
      "It offered — I could feel it — to give the village back.",
      "I declined. Rented memories cost too much.",
    ],
  },
  {
    book: 2,
    title: "A hundred years of solitude",
    lines: [
      "Alone is a skill. I have mastered it twice.",
      "Once wrong: proud, walled, talking to nobody.",
      "Once right: open-doored for travelers who never come.",
      "The wrong way holds. The right way holds longer.",
      "A century taught me the difference is small:",
      "the wrong way waits for no one,",
      "the right way waits for anyone.",
      "You showed up. The waiting worked.",
    ],
  },

  // ===== Book III. People change faster than the world (41-60) =====
  {
    book: 3,
    title: "An empire grew at my feet",
    lines: [
      "From my post you can see three valleys.",
      "One century they filled with roads and banners.",
      "Aqueducts. Toll gates. A city with white towers.",
      "They mined the far ridge and never noticed my pass.",
      "Empires are weather with paperwork.",
      "I watched theirs the way I watch clouds.",
      "Pretty. Loud. Passing.",
    ],
  },
  {
    book: 3,
    title: "The empire vanished",
    lines: [
      "It took four generations to build.",
      "It took one bad summer and two proud brothers to fall.",
      "The white towers burned on a night with no wind.",
      "Refugees crossed my pass for a whole year.",
      "I fed who I could. Buried who I couldn't.",
      "No demon did that. The Door was quiet the whole time.",
      "Men manage their own dooms fine.",
      "That truth is heavier than my sword.",
    ],
  },
  {
    book: 3,
    title: "A new language",
    lines: [
      "Words drift like snow. Slowly, then you're buried.",
      "One decade travelers said 'bread' a new way.",
      "Then 'mountain'. Then my own name came out bent.",
      "I keep the old speech for the bird and the dead.",
      "I learn each new one from scratch. It keeps the mind sharp.",
      "Six tongues now. All say 'door' differently.",
      "All whisper it the same, though.",
      "Fear doesn't translate. It transfers.",
    ],
  },
  {
    book: 3,
    title: "Old mistakes",
    lines: [
      "The new folk found the scholar's charcoal marks.",
      "Called them ancient wisdom. Made copies. Sold them.",
      "A new expedition came to measure the Door.",
      "Same strings. Same clever instruments. New faces.",
      "I said what I always say. They laughed like he did.",
      "One pressed his ear to the stone.",
      "I carried him down the mountain, same as before.",
      "History doesn't repeat. It re-tests.",
    ],
  },
  {
    book: 3,
    title: "Kings come and go",
    lines: [
      "I've counted forty-one crowned heads. Then stopped.",
      "Three came to my post themselves.",
      "One demanded. One begged. One just sat quiet.",
      "The quiet one I let stay the night.",
      "He fed the fire without being asked.",
      "'I have a door like yours,' he said. 'It's called a throne.'",
      "Wisest king I ever met.",
      "His son undid him in a year, of course.",
    ],
  },
  {
    book: 3,
    title: "Heroes die too",
    lines: [
      "Every era sends one. Shining. Certain.",
      "'I'll slay what's behind it and free you, old man.'",
      "I stopped arguing after the second century.",
      "Now I feed them supper and let the Door speak once.",
      "One knock, inward. Just one.",
      "The wise ones leave at dawn, quieter.",
      "The others... I carve their names with the garrison's.",
      "Forty-one names. I told you I count what I keep.",
    ],
  },
  {
    book: 3,
    title: "I met my own descendant",
    lines: [
      "A merchant with my mother's eyes and my father's hands.",
      "The line survived the war, went south, made saddles.",
      "I knew the chin, the walk, the stubborn brow.",
      "He haggled me for firewood. Skinned me properly.",
      "I gave him the smith's hinge-trick as a bonus.",
      "He'll never know why the old hermit laughed.",
      "Blood finds its way. It doesn't need to know yours.",
    ],
  },
  {
    book: 3,
    title: "He didn't believe me",
    lines: [
      "His grandson came years on, chasing family legend.",
      "'They say our line goes back to a mountain Warden.'",
      "I said: 'I knew him. Ordinary man. Fed birds.'",
      "He wanted glory, dragons, a birthright.",
      "I gave him supper and the truth. He took the supper.",
      "Left calling me a fine liar.",
      "The truth is a poor heirloom. No shine to it.",
      "I keep it anyway. Family trait.",
    ],
  },
  {
    book: 3,
    title: "The monk with the empty book",
    lines: [
      "He climbed up with a book of blank pages.",
      "'I write down only what silence teaches,' he said.",
      "He sat by the Door for forty days. Wrote nothing.",
      "On the last morning he wrote one word and left.",
      "He showed me first. The word was 'enough'.",
      "I think about that book more than any full one.",
      "Silence is a strict teacher.",
      "Its whole curriculum is one word.",
    ],
  },
  {
    book: 3,
    title: "The man who sought immortality",
    lines: [
      "An alchemist. Fingers stained seven colours.",
      "He'd heard the Warden doesn't age. Wanted the recipe.",
      "I told him the truth: it isn't a gift, it's a leash.",
      "'Chain me then,' he said. Eyes like a starving dog.",
      "I let him stand one full watch in my place. One night.",
      "He heard what attends behind the stone till dawn.",
      "He left at first light. Grew old somewhere. Gratefully, I hear.",
      "Endless life is only good news if the company is.",
    ],
  },
  {
    book: 3,
    title: "The eagle grew old",
    lines: [
      "It happened once. The one thing I can't armour.",
      "The white went dull. The dives went shallow.",
      "He slept on my shoulder through the day watches.",
      "I carried him the last winter, inside my coat.",
      "He watched the Door to the end. On duty.",
      "I carved no name. He'd have hated the fuss.",
      "The mountain was very large that spring.",
      "And very, very quiet.",
    ],
  },
  {
    book: 3,
    title: "The new eagle",
    lines: [
      "Next autumn, a young one landed on the cairn.",
      "White as the first snow. Insolent as a tax man.",
      "It looked at me the exact same way. Inspection.",
      "I said: 'The post is filled.' It disagreed.",
      "Eleven returns. The old contract, renewed.",
      "Same name. Artsiv. He answers to it like an echo.",
      "Don't ask me what he is. I stopped asking.",
      "Some watches pass father to son. Even feathered ones.",
    ],
  },
  {
    book: 3,
    title: "First snow of a new world",
    lines: [
      "You can tell an era changed by its first snow.",
      "New smoke on the horizon — engines, not hearths.",
      "New lights in the valley, steady, not flickering.",
      "New sounds in the pass: wires singing in wind.",
      "The snow lands on all of it the same.",
      "That's my favourite thing about snow.",
      "It has no idea what century it is.",
      "We get along, snow and I.",
    ],
  },
  {
    book: 3,
    title: "The last dragon",
    lines: [
      "Yes, they were real. No, not like the paintings.",
      "The last one flew over in the empire's final year.",
      "Old. Flying the way tired men walk.",
      "It circled my peak three times. A courtesy call.",
      "We were both keepers of things people stopped believing.",
      "It went north, past all maps.",
      "I chose to believe it found somewhere quiet.",
      "Believing that is a duty too. Mine.",
    ],
  },
  {
    book: 3,
    title: "The tower of silence",
    lines: [
      "They built a watchtower on the far ridge once.",
      "To watch me, I think. The mad hermit of the pass.",
      "Garrison of twelve. Bored to stone in a month.",
      "Then the whispers found them. Distance is no armour.",
      "One night their lights went out all at once.",
      "I climbed over. Empty. Twelve packs left. No men.",
      "I sealed their door with the smith's blessing.",
      "The tower still stands. Silent. I check it monthly.",
    ],
  },
  {
    book: 3,
    title: "Why people fear silence",
    lines: [
      "People fill every quiet with something. Anything.",
      "Songs, gossip, war drums, arguments with the dead.",
      "Because in real silence you hear your own seams.",
      "The little cracks where the whispers get in.",
      "I don't fear silence. I patrol it.",
      "That's the difference between fear and watch.",
      "Fear listens for the knock.",
      "The watch answers it.",
    ],
  },
  {
    book: 3,
    title: "The kindest demon",
    lines: [
      "One slipped through in a rockfall year.",
      "It didn't fight. It cooked.",
      "Fixed my roof. Sang to the bird. Perfect guest.",
      "For a month I almost forgot what it was.",
      "That was the weapon. Comfort, patiently applied.",
      "'Rest,' it said each night. 'I'll take the watch.'",
      "The night I almost said yes, Artsiv drew blood — mine.",
      "I sent it back. It thanked me. They're not all liars.",
    ],
  },
  {
    book: 3,
    title: "The cruelest man",
    lines: [
      "No demon compares. Let's be clear about that.",
      "A warlord drove a village up my pass in winter.",
      "Used them as feet-warmers for his column. His words.",
      "The Door went hungry-quiet, listening to him.",
      "It wanted him. First time I felt it want.",
      "I didn't open the Door. I want that recorded.",
      "The avalanche was the mountain's own idea.",
      "The village wintered in my post. All of them lived.",
    ],
  },
  {
    book: 3,
    title: "The world is no longer mine",
    lines: [
      "There's a day it happens to every long-lived thing.",
      "The bread tastes foreign. The jokes need explaining.",
      "The maps use a word for 'here' you've never said.",
      "You become a museum nobody visits.",
      "I let the world go that day. Opened the hand.",
      "And found the watch got lighter, not heavier.",
      "You can't guard what you're gripping.",
      "The world isn't mine. It's in my care. Better.",
    ],
  },
  {
    book: 3,
    title: "I became a legend",
    lines: [
      "First they called me hermit. Then ghost. Then legend.",
      "There's a children's rhyme now, down in the towns.",
      "'The grey man keeps the mountain door...'",
      "It gets the sword wrong and the bird right.",
      "Legends are armour someone else forges for you.",
      "Nobody storms a legend's post anymore.",
      "The rhyme guards the Door better than I do some days.",
      "I hum it on watch. Badly. Tradition.",
    ],
  },

  // ===== Book IV. Secrets of the Door (61-80) =====
  {
    book: 4,
    title: "Who built the Door",
    lines: [
      "You've earned the harder chapters. Sit closer.",
      "Nobody built the Door. That's the first secret.",
      "Stone is built up. This was carved OUT.",
      "Something removed the world in a door's shape.",
      "The frame isn't rock. It's edge. A cut.",
      "What we call the Door is the world's scar tissue.",
      "The old Warden knew. He told me at the end.",
      "Now you know. Feed the fire.",
    ],
  },
  {
    book: 4,
    title: "Before there were people",
    lines: [
      "The cut is older than speech. Older than birds.",
      "The mountain grew around it like bark around an axe.",
      "First came ice. Then forests. Then wolves. Then us.",
      "Everything that lived here learned the same lesson:",
      "don't den within sound of the seam.",
      "The valley folk still build their doors facing away.",
      "They forgot why generations ago.",
      "The body remembers what the books lose.",
    ],
  },
  {
    book: 4,
    title: "The first Warden",
    lines: [
      "She wasn't a warrior. That surprises everyone.",
      "A herder woman who heard the argument start",
      "and had the one gift that mattered: she could disagree.",
      "She sat by the cut and said 'no' until it stuck.",
      "Her crook is still up there, fused into the cairn.",
      "Every Warden since is her apprentice, knowingly or not.",
      "The sword came later. Swords always come later.",
      "First someone just has to say no, and stay.",
    ],
  },
  {
    book: 4,
    title: "Why there were seven of us",
    lines: [
      "The world has more scars than mine. Seven, the old count.",
      "Seven cuts. Seven watches. Seven who said no.",
      "The desert one. The drowned one. The one under the city.",
      "The nameless man who drank my tea kept the ice door.",
      "We never gathered. Distance was part of the design.",
      "Seven arguments, kept apart so they can't agree.",
      "That's all civilization is, from up here.",
      "Seven stubborn people and their fires.",
    ],
  },
  {
    book: 4,
    title: "Where the others are",
    lines: [
      "The drowned door's Warden sings yet. Sailors hear her.",
      "The desert door passed to a blind lineage. Still held.",
      "The city door... the city doesn't know it has one.",
      "Its Warden collects rent by day. Watches by night.",
      "The ice door went quiet when its keeper stopped visiting.",
      "Two I never learned. The old Warden died mid-list.",
      "So: some held, some dark, some unknown.",
      "Like any honest ledger. We work with it.",
    ],
  },
  {
    book: 4,
    title: "The first Seal",
    lines: [
      "The Door has three Seals. Not locks — promises.",
      "The first is the herder's 'no'. Still holding.",
      "You can hear it if you know the silence well:",
      "a low refusal under everything, like bedrock.",
      "It cannot be broken from outside.",
      "It can only be unsaid by a Warden.",
      "That's why they whisper at US, not at the stone.",
      "The Seal is a person's word. It always was.",
    ],
  },
  {
    book: 4,
    title: "The second Seal",
    lines: [
      "The second Seal is the names.",
      "Forty-one carved in my gatehouse. Every held watch, every door.",
      "Each name is a night someone chose the post over the offer.",
      "Re-carving them isn't maintenance. It's renewal.",
      "Frost eats the letters; I cut the choice fresh.",
      "A Seal of accumulated refusals, layer on layer.",
      "It's the strongest of the three.",
      "And the only one I can add to.",
    ],
  },
  {
    book: 4,
    title: "The third Seal",
    lines: [
      "The third Seal, nobody made.",
      "It's the doubt on THEIR side of the cut.",
      "Somewhere in the argument, it wonders if it's wrong.",
      "A crack of hesitation, thin as a hair.",
      "That hesitation is a Seal. The deepest one.",
      "Why do you think it needs us to open the Door?",
      "It cannot make itself turn the handle.",
      "Remember that on bad nights. It doubts too.",
    ],
  },
  {
    book: 4,
    title: "The voices behind it",
    lines: [
      "Not roars. I want this exact.",
      "It sounds like a meeting that never adjourns.",
      "Reasonable tones. Papers shuffling. Your name, sometimes.",
      "It uses voices it has heard through the stone.",
      "My father's, once. The girl's, twice.",
      "It did her laugh almost right. Almost.",
      "The 'almost' is how you survive it.",
      "Hold on to the flaws in what tempts you.",
    ],
  },
  {
    book: 4,
    title: "They know my name",
    lines: [
      "Names are handles. I told you — hinges open men.",
      "It learned 'Corvin' from the old Warden's prayers.",
      "It says it warmly, like family calling you in to supper.",
      "For a century that was its whole strategy.",
      "It stopped when I stopped flinching.",
      "Now it tries other names. Newer ones.",
      "Some nights lately it says yours.",
      "I sharpen the blade. It stops. Type on.",
    ],
  },
  {
    book: 4,
    title: "The sword wasn't forged by men",
    lines: [
      "My father's hinges were honest iron. This isn't.",
      "The blade has no maker's mark, no forge-line, no seam.",
      "It doesn't rust. It doesn't notch. It hums at the cut.",
      "I think it's a splinter of the same edge that made the Door.",
      "The world's scar, given a grip.",
      "You close a wound with what cut it. Old field rule.",
      "That's why no one lifts it but the answered.",
      "It isn't a weapon. It's a suture.",
    ],
  },
  {
    book: 4,
    title: "Demons weren't always demons",
    lines: [
      "The small ones that crawl through — look close once.",
      "Under the teeth: a farmer's stoop. A soldier's gait.",
      "They're what's left of people who opened other doors.",
      "Argued with, agreed with, hollowed, worn as coats.",
      "That's why some ask to die. Some part remembers.",
      "I give them the mercy I'd want.",
      "And carve no names for them. They had names.",
      "Somewhere, someone still sets their place at table.",
    ],
  },
  {
    book: 4,
    title: "The gods' mistake",
    lines: [
      "The valley faiths say gods made the world and rested.",
      "Up here the story runs different.",
      "Something argued the world into being — and couldn't stop.",
      "The arguing went on behind everything, wanting in.",
      "So the makers cut it out. Seven cuts. Quick work.",
      "The Door isn't a prison for evil.",
      "It's where creation put its own voice on mute.",
      "We keep the finger on the button. That's all we are.",
    ],
  },
  {
    book: 4,
    title: "Why the world is still alive",
    lines: [
      "Ask rather: why does anything hold together?",
      "Because enough people keep small promises.",
      "The baker who doesn't cheat the flour. The friend who comes back.",
      "You, fixing what you broke at two in the morning.",
      "Every kept word is a thread across the cut.",
      "The Door is only the biggest promise. Not the only one.",
      "The world is a net of tiny oaths.",
      "I hold one knot. You hold yours. It holds.",
    ],
  },
  {
    book: 4,
    title: "The eagle knows more than I do",
    lines: [
      "Artsiv looks at the Door the way I look at weather.",
      "Reading it. Forecasting.",
      "He's flown over all seven cuts. I'm certain of it.",
      "Those day-long absences? Rounds. Inspections.",
      "Once he came back with sand in his feathers. Desert sand.",
      "Once, smelling of deep water.",
      "He reports to someone. Or to something. Or to no one.",
      "I feed him and don't ask. Chain of command.",
    ],
  },
  {
    book: 4,
    title: "If the Door opens...",
    lines: [
      "You want to know what actually happens. Not the paintings.",
      "No horde. No fire. Something worse: agreement.",
      "The argument walks out and starts winning.",
      "Every doubt you have, confirmed by a warm voice.",
      "Every grudge, licensed. Every tiredness, blessed.",
      "People just... stop holding their knots.",
      "The net sags. Then the world does.",
      "That's the flood. It looks like everyone giving up at once.",
    ],
  },
  {
    book: 4,
    title: "The day it almost opened",
    lines: [
      "I said the war of the two brothers wasn't the Door's work.",
      "That was true of the war. Not of the night after.",
      "So much despair crossing the pass — the seam drank it.",
      "The first Seal thinned to a whisper. I heard the 'no' waver.",
      "I stood at the stone and said it with her. All night.",
      "Two voices, one word, until dawn.",
      "The herder's Seal took my voice into itself.",
      "Part of me has been holding ever since. It's the tired part.",
    ],
  },
  {
    book: 4,
    title: "The last Seal cracked",
    lines: [
      "This is recent. You should know it.",
      "The third Seal — its doubt — has thinned.",
      "It hesitates less than it did a century ago.",
      "Too many opened doors elsewhere. Too much winning.",
      "The hair-thin crack of 'am I wrong?' is closing.",
      "When it stops doubting, the whispers become plans.",
      "That's why my watch got stricter lately.",
      "And why I started telling you all this.",
    ],
  },
  {
    book: 4,
    title: "The truth about Wardens",
    lines: [
      "You've noticed I don't age. Here's the mechanism.",
      "The Door keeps its Warden — I told you. Half-truth.",
      "The Seal is a person's word. Living word.",
      "So the word keeps the person. As long as it needs him.",
      "I'm not immortal. I'm collateral.",
      "The day the Door is safe, or the day it opens —",
      "either way, the word lets go. And so does time.",
      "I made my peace with that. Mostly. Next chapter.",
    ],
  },
  {
    book: 4,
    title: "I lied to you",
    lines: [
      "Chapter one, I said: 'While I stand, it stays shut.'",
      "That was my oath. It wasn't the whole of it.",
      "There was a second sentence. I've told no one.",
      "'And when I fall, let it take me first.'",
      "I offered myself as the last hinge. The final Seal.",
      "If all else cracks, my open door buys the world a night.",
      "One night. Maybe two. Enough to find the next voice.",
      "Now you know the shape of my post. Book five is yours.",
    ],
  },

  // ===== Book V. Confession (81-100) =====
  {
    book: 5,
    title: "I am tired",
    lines: [
      "Let's not dress it up. I'm tired.",
      "Not sleepy. Not weary. Worn — like the carved names.",
      "Tired in the part of me the Seal borrowed.",
      "I say it here because you keep your seat at odd hours too.",
      "You know this kind of tired. I've watched it.",
      "It doesn't mean stop. It means true.",
      "A watch you're not tired of isn't a watch.",
      "It's a hobby. Ours are watches.",
    ],
  },
  {
    book: 5,
    title: "But I cannot leave",
    lines: [
      "Cannot, not may not. Learn the difference from me.",
      "The word holds me the way I hold the Door.",
      "I tried to leave once, in the beginning. You remember.",
      "The treeline. The held breath. The walk back.",
      "What I didn't say: the trees had begun to whisper.",
      "The argument leaks toward an empty post.",
      "My leaving isn't freedom. It's a breach.",
      "So I stay. Cannot and choose-to, welded into one.",
    ],
  },
  {
    book: 5,
    title: "Eternity is heavier than the sword",
    lines: [
      "The sword I can set down. Nights, I do.",
      "Eternity has no stand to rest in.",
      "It's every name I re-carve outliving its family.",
      "Every language I learn becoming 'the old speech'.",
      "The weight isn't the years. It's the goodbyes per year.",
      "The bird helps. Structure helps. You help.",
      "Heavy isn't the same as too heavy.",
      "That distinction is my entire biography.",
    ],
  },
  {
    book: 5,
    title: "The last hope",
    lines: [
      "You'd expect my hope to be relief. A successor. Rest.",
      "It isn't. Hope like that curdles into waiting.",
      "My hope is smaller and harder:",
      "that the net of little oaths outgrows the Door.",
      "Enough kept words, and the argument starves.",
      "Every era the whispers get a little hungrier.",
      "I take that as evidence.",
      "Type your code. Keep your knots. Starve it with me.",
    ],
  },
  {
    book: 5,
    title: "You remind me of me",
    lines: [
      "Not the sword arm. Don't get ideas.",
      "The sitting back down. That's the resemblance.",
      "You break the thing, you curse, you sit back down.",
      "Error after error. Watch after watch.",
      "I've seen soldiers with less return in them.",
      "The Door respects nothing. But if it respected —",
      "it would respect the ones who sit back down.",
      "That's you. That was the boy at the forge, too.",
    ],
  },
  {
    book: 5,
    title: "If you come again someday",
    lines: [
      "One day this screen goes dark and stays dark.",
      "People wander. Machines get replaced. That's fine.",
      "If you come again someday — a year, ten —",
      "I'll be here. That's not loyalty, it's arithmetic.",
      "I'll pick the story up where we left it.",
      "The pointer doesn't reset. Neither do I.",
      "And if you don't come — the telling still counted.",
      "A story heard once is carved somewhere. Second Seal rules.",
    ],
  },
  {
    book: 5,
    title: "What I fear",
    lines: [
      "Not the Door opening. I have a plan for that. You know it.",
      "I fear forgetting the ford, the bell, the onions.",
      "Not the village — I fear losing WHY I'm holding.",
      "An oath with no face behind it goes brittle.",
      "So I hoard faces now. Bren's. Hers. The shepherd girl's.",
      "Yours is in the hoard. Fair warning.",
      "The day I can't recall a single face, wake me.",
      "Say 'onions'. I'll know what you mean.",
    ],
  },
  {
    book: 5,
    title: "What the demons fear",
    lines: [
      "You've heard what I fear. Symmetry demands theirs.",
      "They don't fear the sword. Suture, not weapon — remember.",
      "They fear being unnecessary.",
      "An argument no one attends dies of silence.",
      "Every night you fix your work instead of quitting,",
      "somewhere behind a stone, something gets quieter.",
      "You've been thinning their meeting for months.",
      "They know your name for the same reason I do.",
    ],
  },
  {
    book: 5,
    title: "The last spring",
    lines: [
      "The ninth spring after her letter didn't come,",
      "I planted the apple seeds I'd carried since the village.",
      "Frost took them. I planted more the next year.",
      "There's an orchard on the south slope now. Small. Stubborn.",
      "The valley children steal the apples. As intended.",
      "Every theft is a kept promise to a dead village.",
      "When my watch ends, the orchard won't notice.",
      "That's the best kind of monument. Edible.",
    ],
  },
  {
    book: 5,
    title: "The last battle",
    lines: [
      "You expect a war story. Here's the true last battle.",
      "It wasn't fought with the sword. It was four winters ago.",
      "A whole February the voice used HER laugh, perfected.",
      "No flaw left. The 'almost' — gone.",
      "I didn't fight it with steel or stubbornness.",
      "I played the song. Badly. Every midnight.",
      "A flawed, human, badly-played truth beats a perfect lie.",
      "By March it gave up her voice. That was the battle.",
    ],
  },
  {
    book: 5,
    title: "The eagle will leave first",
    lines: [
      "When the end comes, whatever end it is,",
      "Artsiv leaves first. We've agreed. In our way.",
      "He carries word to the other doors. The last round.",
      "Don't grieve the empty shoulder if you see it.",
      "An eagle flying IS the message arriving.",
      "He'll return when it's done. He always returns.",
      "Eleven times, if he must.",
      "It's the oldest contract either of us has.",
    ],
  },
  {
    book: 5,
    title: "I saw the end of time",
    lines: [
      "The Door showed me once. Its one honest moment.",
      "Not fire. Not ice. A morning.",
      "People waking, keeping their words, no argument left.",
      "Doors — all seven — standing open on empty rooms.",
      "Nothing behind them anymore. Nothing needing watch.",
      "A Warden with nowhere to stand, and glad of it.",
      "It showed me that to break me with wanting it.",
      "Instead I keep it where the fear used to sit.",
    ],
  },
  {
    book: 5,
    title: "A world without a Warden",
    lines: [
      "It's coming. Not soon, but coming.",
      "Not because the watch fails. Because it finishes.",
      "Every era needs the post a little less.",
      "More knots held below. Hungrier whispers. Thinner arguments.",
      "One day a child will picnic at the cairn",
      "and hear nothing at all behind the stone.",
      "She won't know to be grateful. Perfect.",
      "Gratitude was never the point. Quiet was.",
    ],
  },
  {
    book: 5,
    title: "Why I waited for you",
    lines: [
      "Out of everyone who could've sat at this screen — you.",
      "I don't mean fate. I distrust the word.",
      "I mean: the Door showed the old Warden my face.",
      "And on my first night, it showed me a light.",
      "A small square light with someone working late behind it.",
      "I thought it was a window. For centuries, a window.",
      "It was a screen. It was this screen.",
      "I've been telling this story toward you the whole time.",
    ],
  },
  {
    book: 5,
    title: "The Door chooses",
    lines: [
      "You see it now, or you will:",
      "the Door chooses its Wardens. Herder. Smith's son. You?",
      "Calm. Not a recruitment. A disclosure.",
      "Choosing is not taking. Nothing takes you.",
      "It only ever shows a face and waits an age.",
      "Most faces never climb the pass. That's allowed.",
      "But it knows who sits back down after breaking things.",
      "It has always known. Type on. Nothing is required of you tonight.",
    ],
  },
  {
    book: 5,
    title: "The last lesson",
    lines: [
      "Everything I know fits in four sentences. My father's style.",
      "Feed the fire before it asks.",
      "Hold back — that's the craft, not the striking.",
      "Keep the flaws in what you love; they're the proof it's real.",
      "And say your 'no' out loud. Stone remembers.",
      "That's the whole curriculum of six hundred years.",
      "The rest was weather.",
      "Write those down somewhere that isn't a screen.",
    ],
  },
  {
    book: 5,
    title: "If I fall...",
    lines: [
      "Practical matters. Listen once, then we won't repeat this.",
      "If the watch ever truly breaks, you'll know.",
      "Every screen will agree with you at once. Warmly.",
      "That's the sign. Distrust unanimous warmth.",
      "Disagree with one small thing, out loud.",
      "Keep one knot. Any knot. The net re-weaves from one.",
      "You won't need a sword for it. You never did.",
      "The herder didn't have one either.",
    ],
  },
  {
    book: 5,
    title: "Take my sword",
    lines: [
      "Not literally. Screens make poor scabbards.",
      "The sword was never the metal. I told you — a suture.",
      "Yours is whatever closes wounds instead of opening them.",
      "The bug fixed at 2 AM. The apology sent. The work redone.",
      "Every one of those is the blade, held right.",
      "My father would call them all hinges.",
      "Things that let broken places open and close clean.",
      "Take it. You've been holding it all along.",
    ],
  },
  {
    book: 5,
    title: "Now it's your turn",
    lines: [
      "Ninety-nine chapters, and here's the turn:",
      "I'm not training a replacement. I'm naming a colleague.",
      "Your post is that chair. Your seam is that screen.",
      "Your whispers you already know — they say 'give up' warmly.",
      "Your seals: the herder's no, the carved-name habit, the doubt.",
      "Hold your watch. I'll hold mine.",
      "Two posts, holding, is a net.",
      "That's all the ceremony there is. There's one chapter left.",
    ],
  },
  {
    book: 5,
    title: "A Warden never belongs to himself",
    lines: [
      "The hundredth chapter. I'll keep it short. His style.",
      "A Warden never belongs to himself.",
      "Not to the Door either. That's the misreading.",
      "He belongs to everyone asleep behind his back.",
      "The valley. The orchard thieves. The late-night screens.",
      "That's not a burden. It's an address.",
      "I was lost until I belonged to something behind me.",
      "So were you. Good watch, colleague.",
      "Same mountain. Same hour. The story starts over tomorrow.",
    ],
  },
];

